language: julia
julia:
    - 1
    - nightly
before_install:
    - sudo apt-get install python3-matplotlib
after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
## uncomment the following lines to override the default test script
#script:
# - julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test()'
